name: AGW Build & Publish
on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]
jobs:
  agw-build:
    name: agw build job
    needs:
      [
        orc8r-build
      ]
    runs-on: ubuntu-20.04
    steps:
      env:
        ORC8R_ARTIFACTS: ${{ needs.orc8r-build.outputs.artifacts }}
      run: |
        echo ${ORC8R_ARTIFACTS}
      
